### ISSUE TITLE
yices_push failed in sha_resolver

### ISSUE THREAD

**Issue by bronning18** [ucsb-seclab/jackal#1]
When trying to run jackal on a vulnerable Rico contract(https://arbiscan.deth.net/address/0xc6d7b37fe18a3dd007f9b1c3b339b8c6043b3ccf#code
vat.sol → line 295) I get an execution error in attempt self.sha_resolver.fix_shas(). It is related to the pop() call in yices2

**Comment by degrigis** [comment]
Hey there! 

So the sha_resolver uses the SimState `state_at_call` to "fix" the shas's buffers. 

The problem you are facing happens when this SimState is `unsat`, therefore no pop() or push() can be done on the solver anymore. To be safe, before fixing the shas, you should check if the state you are operating on is sat or not.
